### ISSUE TITLE
Multiple azure key vault kms block causes conflicts in plugin binary and the server fails to start

### ISSUE THREAD

**Issue by jchenship** [hashicorp/boundary#2340] opened 2022-08-09 01:05 UTC
**Describe the bug**
Got an error 
```
$ sudo -u boundary /usr/bin/boundary server -config /etc/boundary/controller.hcl
Error parsing KMS configuration: error writing out plugin for execution: open /var/run/boundary/plugin-exec/boundary-plugin-kms-azurekeyvault.gz: text file busy
```
when using the following config 

```
disable_mlock = true

controller {
  name = "vm-tools-stg-boundary-main000001"
  database {
    url = "{{ boundary_controller_database_url }}"
  }
}

listener "tcp" {
  purpose = "api"
  address = "10.45.100.68"

  tls_disable = true
}

listener "tcp" {
  purpose = "cluster"
  address = "127.0.0.1"

  tls_disable = true
}

plugins {
  execution_dir = "/var/run/boundary/plugin-exec"
}

kms "azurekeyvault" {
  purpose        = "root"
  tenant_id      = "{{ tenant_id }}"
  client_id      = "{{ boundary_azure_client_id }}"
  vault_name     = "kv-tools-stg-vault-main"
  key_name       = "boundary-root"
}

kms "azurekeyvault" {
  purpose        = "worker-auth"
  tenant_id      = "{{ tenant_id }}"
  client_id      = "{{ boundary_azure_client_id }}"
  vault_name     = "kv-tools-stg-vault-main"
  key_name       = "boundary-worker-auth"
}

kms "azurekeyvault" {
  purpose        = "recovery"
  tenant_id      = "{{ tenant_id }}"
  client_id      = "{{ boundary_azure_client_id }}"
  vault_name     = "kv-tools-stg-vault-main"
  key_name       = "boundary-recovery"
}
```

but if I remove the `worker-auth` and `recover` kms , the server starts fine 

**To Reproduce**

See above 

**Expected behavior**

As suggested by https://github.com/hashicorp/boundary/blob/main/website/content/docs/getting-started/installing/production.mdx , we should be able to configure several kms blocks for different purposes

**Additional context**

**Comment by jefferai** [comment] 2022-08-10 18:01
Closing as duplicate of #2343 as it's the same underlying cause.

**Closed by jefferai** 2022-08-10 18:01 UTC
