### ISSUE TITLE
Workers Resolve Controller DNS to IP Addresses

### ISSUE THREAD

**Issue by micchickenburger** [hashicorp/boundary#1905] opened 2022-03-10 19:44 UTC
**Is your feature request related to a problem? Please describe.**
Yes, we have a race condition in our infrastructure.  We have n workers in one subnet and m controllers in another subnet with a network load balancer in between.  The workers are configured to use the internally-resolved domain name for the network load balancer, e.g.:

```hcl
# https://www.boundaryproject.io/docs/configuration/worker
worker {
  name = "worker-k3eb39la6v"
  description = "Boundary Worker"

  controllers = ["hostname-nlb-<random>.elb.<region>.amazonaws.com"] # Point to the NLB private IP in the same subnet
  public_addr = "<redacted>"
}

listener "tcp" {
  address = "10.15.0.7"
  purpose = "proxy"
  tls_disable = false
  tls_key_file = "/etc/pki/tls/boundary/key.pem"
  tls_cert_file = "/etc/pki/tls/boundary/cert.crt"
}

kms "awskms" {
  purpose = "worker-auth"
  key_id = "global_root"
  kms_key_id = "<redacted>"
}
```

On the host the NLB domain name resolves to several IP addresses:

```bash
$ nslookup hostname-nlb-<random>.elb.<region>.amazonaws.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	hostname-nlb-<random>.elb.<region>.amazonaws.com
Address: 10.15.0.112
Name:	hostname-nlb-<random>.elb.<region>.amazonaws.com
Address: 10.15.2.199
```

These addresses change over time based on replaced controllers, eventually causing the worker to disconnect from all controllers.  This also happens during an infrastructure deploy where only the worker and controller servers are replaced, perhaps due to system upgrades.  The new instances start before the old ones are removed to prevent a service outage, but once the workers start up they seem to cache the old IP addresses from DNS resolution without ever learning about the new ones.  Also I'm not confident the worker uses _all_ returned IP addresses from name resolution, preventing redundancy.

**Describe the solution you'd like**
I'd like for the workers to periodically update their list of controllers from name resolution.  I don't know how else to solve this race condition.

**Describe alternatives you've considered**
I've considered tearing down the entire infrastructure every time the app servers need to be updated.  I've also considered using timers to wait an arbitrary amount of time before starting the workers.

**Explain any additional use-cases**
This would make the boundary infrastructure more resilient and self-healing as the infrastructure around the workers changes.

**Additional context**
Errors seen in the worker logs:

```
Mar 10 15:56:46 ip-10-15-0-7 boundary[846]: {"id":"KDFA8XqJ7r","source":"https://hashicorp.com/boundary/us-east-2-worker-k3eb39la6v","specversion":"1.0","type":"error","data":{"error":"rpc error: code = Unavailable desc = last connection error: connection error: desc = \"transport: Error while dialing unable to dial to controller: dial tcp 10.15.2.159:9201: i/o timeout\"","error_fields":{},"id":"e_nbJBRmXvOU","version":"v0.1","op":"worker.(Worker).sendWorkerStatus","info":{"msg":"error making status request to controller"}},"datacontentype":"application/cloudevents","time":"2022-03-10T15:56:46.56174218Z"}
Mar 10 15:56:46 ip-10-15-0-7 boundary[846]: {"id":"xIh3BBUyzi","source":"https://hashicorp.com/boundary/us-east-2-worker-k3eb39la6v","specversion":"1.0","type":"error","data":{"error":"status error grace period has expired, canceling all sessions on worker","error_fields":{},"id":"e_KP5KFY653n","version":"v0.1","op":"worker.(Worker).sendWorkerStatus","info":{"grace_period":15000000000,"last_status_time":"2022-03-10 14:06:23.131231818 +0000 UTC m=+82334.597657530"}},"datacontentype":"application/cloudevents","time":"2022-03-10T15:56:46.561907996Z"}
```

At the time of this error, there was no system with IP address `10.15.2.159` since it was replaced a day before.

**Comment by malnick** [comment] 2022-03-30 17:15
Thanks for raising this @micchickenburger, I have a few follow up questions about the deployment and testing you've done so far.

First thing, are you running anything that might provide DNS caching on the host such as dnsmasq or bind 9? 

> The new instances start before the old ones are removed to prevent a service outage, but once the workers start up they seem to cache the old IP addresses from DNS resolution without ever learning about the new ones.

How long are you waiting after taking the old instances down? This could be caused by DNS not being updated yet, since the new instances would likely have their IPs appended, they'd be last IPs the worker would try, I'm wondering if you're seeing the worker try that next set in the logs? 

Have you tried doing a reverse DNS lookup on the IP's from the worker host to ensure they resolve to the domain name that you expect? I'm not an expert in AWS networking but I think NLBs can route based on availability zone, but I think that requires appending the AZ to the domain name (and I don't see you doing that in the configuration example). Might be worth sanity checking the IP resolves to the domain you expect from the worker anyways, just to rule out strange DNS behavior. 

> Also I'm not confident the worker uses all returned IP addresses from name resolution, preventing redundancy.

Can you add more details about this? What data is giving you this impression.

Thanks again, I know this is a ton of follow up questions. To be clear, we don't cache IPs, so we need to dig into the network topology and other areas.

**Comment by micchickenburger** [comment] 2022-04-15 19:28
@malnick Hi Jeff, I got an email notification with your response but don't see it here.  At any rate, we don't use dnsmasq or bind9, but I think systemd on Ubuntu Focal Fossa (which is our base image) has some sort of intermediary caching mechanism.  You are right that DNS is not updated yet when the workers come online.  That's the source of this problem:  How can I allow workers and controllers to scale in separate autoscaling groups or tear one group down and bring back up without restarting Boundary services by hand?

Reverse DNS lookups do work properly; we are using Amazon-provided DNS.  NLBs can route by AZ but I do want all workers to be able to connect to all controllers for redundancy.

I'll see if I can provide evidence about my suspicion that workers don't use all the returned IP addresses from DNS resolution.

**Comment by jefferai** [comment] 2022-05-16 16:32
Go's stdlib DNS resolver does not cache DNS lookups; however, this is not the default resolver if your Boundary binary was built with CGO enabled. Our own releases are built with CGO disabled on every platform that supports it (some do not) -- you can check by using `file` to see if it's a static binary or not. If you're using a CGO-enabled binary, it will by default defer to your OS DNS resolution capability, usually through libc -- and that often _does_ cache responses. If that's the case, you'll either need to turn off DNS caching at an OS level, or you will need to use `GODEBUG=netdns=go` when launching the program.

**Comment by micchickenburger** [comment] 2022-05-16 16:43
Thanks for these details.  We use the prebuilt Boundary binaries.  How often does the Boundary executable cause a DNS lookup to be performed?  For instance, if on startup a Boundary worker connects to two controllers but some time later both controllers are replaced, how can the Boundary worker connect to the new controllers without being manually restarted?

**Comment by jefferai** [comment] 2022-05-17 17:06
Workers are given the current controller information on each status update which happens every few seconds. The `controllers` value in the config serves as initial ingress to connect to one or more controllers, but once connected they use the current set of controllers' advertised cluster addresses. 

You may want to ensure the [public cluster addr](https://www.boundaryproject.io/docs/configuration/controller#public_cluster_addr) is set to the desired DNS address, otherwise the controller will use its current cluster listener address as the address advertised to workers. Note that setting these all to the same DNS value (e.g. a load balancer with a single ingress address) is not usually ideal as it will cause the worker to connect only to one controller, negating the round-robbin-ing/HA capabilities.

**Comment by jefferai** [comment] 2022-05-18 02:49
I think we're going to be changing that to be `initial_upstreams` in an upcoming version which along with updated help text will make this more clear.

**Comment by jefferai** [comment] 2022-06-22 19:38
We've updated to `initial_upstreams` in 0.9.0. I'm going to close this; please feel free to reopen if there are still additional concerns.

**Closed by jefferai** 2022-06-22 19:38 UTC
