### ISSUE TITLE
managed groups don't get role grants

### ISSUE THREAD

**Issue by jwueste** [hashicorp/boundary#1823] opened 2022-01-17 12:04 UTC
Hi,

it seems as if users from managed groups dont' get any role grants.
Im deploying the configuration via terraform, here is what I've done:

1. Create auth method
`
resource "boundary_auth_method_oidc" "provider" {
  name                 = "Azure"
  description          = "OIDC auth method for Azure"
  scope_id             = boundary_scope.global.id
  issuer               = "https://sts.windows.net/<<TENANT_ID>>/"
  client_id            = "<<SERVICEPRINCIPAL_APP_ID>>"
  client_secret        = "<<SERVICEPRINCIPAL_SECRET>>"
  signing_algorithms   = ["RS256"]
  api_url_prefix       = "https://<<BOUNDARY_URL>>:9200"
  is_primary_for_scope = true
}
`

2. Create managed group
`
resource "boundary_managed_group" "azureops" {
  name = "azureops"
  description = "Managed group for AzureOps"
  auth_method_id = boundary_auth_method_oidc.provider.id
  filter = "\"<<OBJECT_ID_OF_AAD_GROUP>>\" in \"/userinfo/groups\""
}
`
3. create roles for projects
`
resource "boundary_role" "readOnlyLandingzones" {
  for_each      = var.landingzone_subscriptions
  name          = "read-only-${each.key}"
  description   = "LZ read-only permission"
  scope_id      = boundary_scope.landingzones[each.key].id
  principal_ids = [boundary_user.someuser.id, boundary_managed_group.azureops.id]
  grant_strings = ["id=*;type=*;actions=read,,list"]
}
`

When a member of referenced AAD-group logs on into boundary, the corresponding user object is created

![image](https://user-images.githubusercontent.com/37145409/149766199-b2c0e2d1-011c-4868-9e4a-ebda00b47ada.png)

and is displayed as member of the managed group:
![image](https://user-images.githubusercontent.com/37145409/149766105-2dc19e8f-c78e-4c47-86c7-66511a37ab9f.png)

But the users don't have the defined role assigned and can't see any project.

Best,
Jonas

**Comment by Alan-pad** [comment] 2022-01-20 09:39
@jwueste I stumbled upon the same issue, the `boundary_auth_method_oidc` resource in terraform set the claims scope to openid only by default you should had other claims scope to enable Boundary to make yout filter work.

To debug that I found that using the CLI to read the account and see the token claims helped me a lot ! 
You can try using the following commands :

```
boundary accounts list -auth-method-id=<YOUR_ID>
boundary accounts read -id=<ID_OF_ACCOUNT>
```

Hope that helps you !

**Comment by Alan-pad** [comment] 2022-01-20 09:45
Oh I misread your issue, thought it didn't work in the association to the managed groups

**Comment by Alan-pad** [comment] 2022-01-20 09:50
From your code, I infered that `boundary_scope.landingzones[each.key].id` is a project, my guess would be that you gave access to all subresources but not the top-level resource which are projects

**Comment by jefferai** [comment] 2022-01-24 21:59
You may want to try using the CLI to explore the managed groups that are create and see which account(s) are (or are not) being added to them.

If no accounts are being added to the managed groups it's likely an issue with the filter -- as @Alan-pad suggested reading the account and looking at the claims can help significantly. If the accounts are added to the managed group then it may be an issue with the set of permissions you're granting in and of itself, or, as @Alan-pad suggested, the scopes you're granting them in.

**Comment by jwueste** [comment] 2022-03-24 09:55
Just found the issue.
When using AAD as an OIDC Provider, users groups shown in userinfo aren't exported as a list, but all groupIDs in one string.
Switching the filter to token claims resolved it. 
Sorry for any caused confusion...

**Comment by xingluw** [comment] 2022-05-02 19:48
Closing as a duplicate of: https://github.com/hashicorp/boundary/issues/1771

**Closed by xingluw** 2022-05-02 19:48 UTC
Labels: triage
